### ISSUE TITLE
self.review_set

### ISSUE THREAD

**Issue by arriqaaq** [jadianes/winerama-recommender-tutorial#2]
Could you please describe where the review_set is defined? In the models.py file, under the wine table, you've used this, self.review_set

**Comment by jadianes** [comment]
Hi,

The `review_set` field is automatically provided by Django. Every model class (extending `models.Model`) that is referenced by other model class in a one-to-many relationship will have such fields named using the name of the "many" side followed by `_set`. For example, in our case we have `reviews_set` in every Wine instance because the `Review` class defined a field as:  

```
wine = models.ForeignKey(Wine)
```

That is, we defined a many (`Review`) to one (`Wine`) relationship between both classes. From the review part we simply access the wine by using the `wine` field (there is just one wine). From the wine side, since we have potentially many reviews, we need to use the `reviews_set` generated by Django.  

Hope that helps!

**Comment by arriqaaq** [comment]
This was of great help jadianes! Thank you

**Comment by jadianes** [comment]
My pleasure @arriqaaq
